sudo: required
dist: xenial

notifications:
  email: false

language: python
python: '3.6'
cache: pip

install:
  # Install latest ghostscript from binary on https://www.ghostscript.com/download/gsdnld.html
  - wget https://github.com/ArtifexSoftware/ghostpdl-downloads/releases/download/gs927/ghostscript-9.27-linux-x86_64.tgz
  - tar xvf ghostscript-9.27-linux-x86_64.tgz
  - sudo mv ghostscript-9.27-linux-x86_64/gs-927-linux-x86_64 /usr/bin/gs
  # tox
  - pip install tox
script:
  - tox
